---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Change Password
    user:
      name: root
      password: "{{ root_pwd | password_hash('abcd') }}"
      update_password: always
