---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
- name: Add group "nixadmins" to remote server
     group:
       name: nixadmins
       gid: 2010
       state: present

   - name: Add group "Office" to remote server
     group:
       name: office
       gid: 2011
       state: present

   - name: Add group "Warehouse" to remote server
     group:
       name: warehouse
       gid: 2012
       state: present 

   - name: Add user "sysadmin" to remote server
     user:
       name: sysadmin
       comment: "Privileged User"
       uid: 2001
       group: nixadmins
       groups: office,warehouse
       append: yes
